# NumPy学习

**Table of Content**
* 属性
* 创建
    * 随机数
* 运算
    * 聚合函数
* 索引
* 数组操作
* 拷贝

[Numpy中文网](https://www.numpy.org.cn)

采用C语言编写，采用矩阵运算，消耗资源少，比自带数据结构的运算款很多

## 属性

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [3]:
# 维度
print(array.ndim)

# 行列数
print(array.shape)

# 元素个数
print(array.size)

2
(2, 3)
6


## 创建

In [8]:
# 指定数据类型
a = np.array([1, 2, 3], dtype=np.int32)
b = np.array([1, 2, 3], dtype=np.float64)

print(a)
print(b)

[1 2 3] [1. 2. 3.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]


In [9]:
# 快速创建
zero = np.zeros((3, 4))
one = np.ones((2, 3), dtype=np.int32)
empty = np.empty((2, 3))        # 接近零的数

print(zero)
print(one)
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


In [13]:
# 连续数字
arange = np.arange(1, 10, 2)        # 步长为2

# 线段形数据
linspace = np.linspace(1, 10, 8)   # 分割成8个点

# 改变形状
reshape = np.arange(20).reshape(4, 5)   # 参数为-1则会自动计算

print(arange)
print(linspace)
print(reshape)

[1 3 5 7 9]
[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### 随机数

In [131]:
# 0~1间的浮点数
r = np.random.rand(2, 3)
print("rand: ", r)

# 0～1间均匀取样随机数
r = np.random.random((2, 4))
print("random: ", r)

# [0, 10)间的随机整数
r = np.random.randint(10)
print("randint: ", r)

# 基于给定值生成随机数
r = np.random.choice([3, 5, 7, 9], size=(2, 3))
print("choice: ", r)

# 均匀分布随机数 [low, high)
r = np.random.uniform(1, 10, (3, 2))
print("uniform: ", r)

# 标准正态分布 均值0 方差1
r = np.random.randn(3, 2)
print("randn: ", r)

# 正态分布 均值10 方差1
r = np.random.normal(10, 1, (3, 2))
print("normal: ", r)

rand:  [[0.44155749 0.44601869 0.05318859]
 [0.28594465 0.72112534 0.91809614]]
random:  [[0.07914297 0.68466181 0.49258672 0.1509604 ]
 [0.63843674 0.85319365 0.3285023  0.60701208]]
randint:  2
choice:  [[3 9 9]
 [7 3 5]]
uniform:  [[2.87500892 9.01628853]
 [1.99811272 3.47776626]
 [7.94675885 4.08628526]]
randn:  [[-0.8897855   0.66911561]
 [ 1.32854304  0.34210128]
 [-1.62014918 -0.21174625]]
[[10.49353599 10.8195831 ]
 [ 9.44557101  8.93493195]
 [10.00297058  9.5695596 ]]


## 运算

In [26]:
a = np.array([[1,2], [3, 4]])
b = np.arange(4).reshape((2,2))

# 矩阵乘法
print(np.dot(a, b))
print(a.dot(b))

# 对位乘法
print(a * b)

print(a ** 2)

[[ 4  7]
 [ 8 15]]
[[ 4  7]
 [ 8 15]]
[[ 0  2]
 [ 6 12]]
[[ 1  4]
 [ 9 16]]


In [27]:
# 一些数学函数
e = np.sin(a)
print(e)

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [28]:
# 逻辑判断
print(b < 3)

[[ True  True]
 [ True False]]


### 聚合函数

In [154]:
r = np.random.randint(0, 100, (2, 5))
print(r)

print("sum: ", np.sum(r))
print("sum[axis=0]: ", np.sum(r, axis=0))    # 列为方向
print("sum[axis=1]: ", np.sum(r, axis=1))    # 一行运算一次

print("min: ", np.min(r))
print("min[axis=0]: ", np.min(r, axis=0))
print("min[axis=1]: ", np.min(r, axis=1))

print("argmax: ", np.argmax(r))
print("argmax[axis=0]: ", np.argmax(r, axis=0))
print("argmax[axis=1]: ", np.argmax(r, axis=1))

print("mean: ", np.mean(r))
print("average: ", np.average(r))
print("median: ", np.median(r))

[[ 7 60 21 79 84]
 [72 82 40 36  1]]
sum:  482
sum[axis=0]:  [ 79 142  61 115  85]
sum[axis=1]:  [251 231]
min:  1
min[axis=0]:  [ 7 60 21 36  1]
min[axis=1]:  [7 1]
argmax:  4
argmax[axis=0]:  [1 1 1 0 0]
argmax[axis=1]:  [4 1]
mean:  48.2
average:  48.2
median:  50.0


In [156]:
r = np.random.randint(0, 10, (2, 3))
print(r)

# 将非零元素的行与列分隔开，冲构成两个分别关于行与列的矩阵
print(np.nonzero(r))

[[6 1 0]
 [8 8 9]]
(array([0, 0, 1, 1, 1]), array([0, 1, 0, 1, 2]))


In [160]:
a = np.arange(6, 0, -1).reshape(2, 3)
print(a)

print(np.sort(a))           # 行内排序
print(np.sort(a, axis=0))   # 列内排序


[[6 5 4]
 [3 2 1]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [161]:
# 两种转置表达方式
print(np.transpose(a))
print(a.T)

[[6 3]
 [5 2]
 [4 1]]
[[6 3]
 [5 2]
 [4 1]]


In [165]:
# 将数组中过大过小的数据进行裁切
a = np.arange(0, 10).reshape(2, 5)
print(a)

# 小于3的都变为3， 大于8的都变为8
print(np.clip(a, 3, 8))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[3 3 3 3 4]
 [5 6 7 8 8]]


## 索引

In [171]:
a = np.arange(6)

print(a)
print(a[1])

a = a.reshape((2, 3))
print(a)
print(a[1])     # 矩阵的第二行
print(a[1][2], a[1, 2])     # 第二行第三个元素（两种表示）

[0 1 2 3 4 5]
1
[[0 1 2]
 [3 4 5]]
[3 4 5]
5 5


In [175]:
# 切片
print(a)
print(a[1, 1:3])
print(a[:, 1])

[[0 1 2]
 [3 4 5]]
[4 5]
[1 4]
[[0 1 2]
 [3 4 5]]


In [183]:
# 遍历
for row in a:
    for item in row:
        print(item, end=" ")

print()

for item in a.flat:         # a.flatten() 将多维矩阵展开成1行的矩阵
    print(item, end=" ")

0 1 2 3 4 5 
0 1 2 3 4 5 

## 数组操作

In [185]:
# 合并
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])

# 垂直拼接
print(np.vstack((a, b)))

# 水平拼接
print(np.hstack((a, b)))

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [194]:
# 添加维度
# 一维数组转置会没有效果的
print(a.T)

print(a[np.newaxis, :])     # 一行三列
print(a[:, np.newaxis])     # 三行一列

print(a[np.newaxis, :].T)
print(a[:, np.newaxis].shape)

[1 1 1]
[[1 1 1]]
[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]]
(3, 1)


In [200]:
# 合并多个矩阵
a, b = np.array([1, 1, 1]), np.array([2, 2, 2])
a, b = a[:, np.newaxis], b[:, np.newaxis]

print(np.concatenate((a,b,b,a), axis=0))
print(np.concatenate((a,b,b,a), axis=1))


[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [206]:
# 分割
a = np.arange(12).reshape(3, -1)
print(a)

# 横向切
print(np.split(a, 3, axis=0))
print(np.vsplit(a, 3))

# 纵向切
print(np.split(a, 2, axis=1))
print(np.hsplit(a, 2))

# 不等量切割
print(np.array_split(a, 3, axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


## 拷贝

In [208]:
# 浅拷贝
a = np.arange(3)
b = a
b[1] = 100
print(a, b, b is a)

[  0 100   2] [  0 100   2] True


In [210]:
# 深拷贝
b = a.copy()
a[2] = 99
print(a, b, a is b)

[  0 100  99] [  0 100  99] False
